consume-config-ms
endava-pad-backend-microservices/audit pull request #6
Opened 2019-06-06 17:22 UTC by josesolaro

2019-06-06 17:30 UTC, nestorreloaded requested changes
Please review the changes

2019-06-06 17:30 UTC, nestorreloaded commented on Audit/Repository/AuditRepository.cs
> +                /*RestClient client = new RestClient(ConnectionDB.ConnectionString);
Please remove commented code (only should be use for documentation)

2019-06-06 17:30 UTC, nestorreloaded commented on Audit/Repository/AuditRepository.cs
> +            }catch(Exception e)
We should log exception messages

2019-06-06 17:30 UTC, nestorreloaded commented on Audit/Services/ConfigService.cs
> +                return null;
Please don't return null, it leads to a lot of Exceptions

2019-06-06 17:30 UTC, nestorreloaded commented on Audit/Startup.cs
> +                if (my_conf.ContainsKey("AUDIT:NOTTOSAVE:" + i))
Please, put hardcoded strings into constants

2019-06-06 17:30 UTC, nestorreloaded commented on Audit/Utils/Utils.cs
> +                return null;
Please don't return null

2019-06-06 17:30 UTC, nestorreloaded commented on Audit/Services/ConfigService.cs
> +            return new object();
The body parameter isn't used in this method

2019-06-06 17:30 UTC, nestorreloaded commented on Audit/Dockerfile
> +GATEWAY_URL=localhostossss:8080 \
It shouln't be 'localhost' instead ?

2019-06-06 22:14 UTC, nestorreloaded approved these changes

2019-06-07 18:52 UTC, exe135 approved these changes

2019-06-10 15:26 UTC, merged